GDG-on-Campus-KNU/GDG_onCampus_KNU_Official_FE

src/Router.tsx
src/components/Button/SigninBtn.tsx
src/components/Typography/Title.tsx
src/components/auth/AuthModal.tsx
src/pages/signin/components/SigninModal.tsx
src/pages/signup/SignupPendingPage.tsx
src/pages/signup/components/SignUpForm.tsx

--- 
- #19
- 컴포넌트 하위 폴더명 수정(소문자로 통일)
- 라우터 경로 수정
---
---

컴포넌트 하위 폴더명 수정 및 라우터 경로 수정

---

src/Router.tsx
src/components/button/CommonBtn.tsx
src/interface/ButtonInterfaces.ts
src/pages/apply/ApplyExPage.tsx
src/pages/apply/ApplyPage.tsx
src/pages/apply/components/ApplyNav.tsx
src/pages/apply/components/ApplyNavBox.tsx
src/styles/ApplyStyle.ts
src/styles/LayoutStyle.ts

---
- 네비 지원서 페이지 구현
---
---
x
close #32

지원서 네비 페이지 구현

---

src/components/button/CommonBtn.tsx
src/components/button/CompleteBtn.tsx
src/components/button/MobileBtn.tsx
src/styles/GlobalStyle.ts

--- 
- 버튼 컬러 케이스 수정 및 통일
---
- 없음
---
- 없음
#40

Style: 버튼 세부 디자인 수정

---

src/components/feature/header/MainNavigation.tsx
src/components/feature/header/NavigationSlideMobile.tsx
src/components/feature/header/StatusDropDownItems.tsx
src/pages/mypage/MyPage.tsx
src/store/useHeaderDropDownStore.ts

---
- 마이페이지 모바일 헤더 구현
- 전역 상태 관리 빼기
- 드롭다운 버튼 전역 상태관리 뺴기
- Status에 따른 드롭다운 박스 구현
---
---
x
close #50

모바일 드롭 다운 버튼 구현 및 전역 상태 구현

---

src/pages/mypage/MyPage.tsx
src/pages/mypage/hooks/useUserInfo.tsx
src/styles/GlobalStyle.ts

- 마이페이지 사용자 정보 조회 및 수정 기능 구현
- 회원가입 시 입력했던 정보를 마이페이지에서 조회 가능
- 소속팀 부분에 스크롤바가 보이지 않는 문제를 해결하기 위해 글로벌 css 파일에 정의되어 있는 스크롤바 display:none을 visibility:hidden으로 변경
- 아직 프로필 사진 등록 기능 구현되지 않음

마이페이지 사용자 정보 조회 및 수정 기능 구현

---

src/apis/hooks/mypage/useGetMyData.ts
src/components/feature/footer/MainFooter.tsx
src/pages/apply/components/ApplyForm.tsx
src/pages/apply/components/ApplyQualify.tsx
src/pages/apply/components/ApplySaveForm.tsx
src/styles/GlobalStyle.ts

---
- Scrollbar css 수정
- 조건에 따른 Query 발동
- console.log 삭제
- footer -> a 태그 변경
---
- QA 1차 수정입니다.
---
x
close #60

QA 1차 수정 PR

---

.github/workflows/deploy.yml
.gitignore

---
- .env파일 경로 설정 및 부여
---
- develop 머지후 구글 태그 매니저 달것
---
x
close #84

deploy파일 수정

---

index.html
naverf73293df57ba8f81aba3732f06ce5471.html

---
- 네이버 웹 서치어드바이저 파일 업로드 및 수정
---
---
close #88

네이버 웹 서치어드바이저 파일 업로드 및 수정

---

src/pages/admin/components/docs/ApplyDetailModal.tsx

- 지원자의 지원 서류 답변 내용을 4개 모두 볼 수 있도록 수정
---
---
---
closes #90

서류하기 모달 부분 수정

---

src/pages/introduce/components/FieldTable.tsx

Release v.1.0.4

---

src/pages/admin/components/docs/ApplyDetailModal.style.ts
src/pages/admin/components/docs/ApplyDetailModal.tsx
src/pages/apply/components/ApplyDocs.ts

- 지원 서류 modal 창 닫기 button 수정
- 지원 마감 날짜 수정
---
---
---
closes #102

8월 19일 버그수정 (1)

---

src/components/common/img/LazyLoadingImg.tsx
src/pages/admin/AdminDocConfirmPage.tsx
src/pages/admin/AdminTeamArrangePage.tsx
src/pages/admin/components/docs/AdminConfirmTable.tsx
src/pages/admin/components/docs/TableSection.tsx
src/pages/admin/components/team/CreateTeamToken.tsx
src/pages/main/MainPage.tsx
src/pages/main/components/MainRound.tsx
src/pages/main/components/PCRotateCarousel.tsx
src/pages/main/components/RotateCarousel.style.ts
src/pages/main/components/RotateCarousel.tsx
src/pages/main/components/Tablet/TabletRotateCarousel.tsx
src/router/Router.tsx

---
- lazy loading을 통한 초기속도 페이지 렌더링 최적화
- 페이지별 렌더링 최적화
---
- 현재 배포 페이지 초기 렌더링 속도
- 페이지 최적화 후 렌더링 속도
---
x
close #105

렌더링 최적화 및 이미지 최적화

---

src/apis/hooks/apply/ApplyInquiryAPI.ts
src/components/common/button/CommonBtn.tsx
src/components/feature/header/NavigationSlideMobile.tsx
src/pages/ErrorPage.tsx
src/pages/apply/components/InquiryModal.tsx
src/pages/main/components/Content.tsx
src/types/ErrorInterface.ts

---
- 서류 모달창 예외처리 구현
- 모바일 서류 페이지 무한루프 수정
---
x
---
x
close #107

Feat/issue #107

---

src/components/feature/header/MainNavigation.tsx
src/components/feature/header/MainNavigationMobile.tsx
src/components/feature/header/NavigationSlideMobile.style.ts
src/components/feature/header/NavigationSlideMobile.tsx
src/components/feature/header/StatusDropDownItems.tsx
src/pages/CommingSoonPage.tsx
src/pages/RootPage.tsx
src/pages/apply/components/ApplyNavBox.tsx
src/router/Router.tsx

---
- Comming Soon 화면 제작
---
- MainNavigation.tsx 
- NavLink -> Link로 수정
- 모바일 Navigation 컴포넌트 분리
- RootPage 네비게이션 컴포넌트 lazy loading 적용
- MobileSlide lazy 로딩 적용
---
- 모바일 슬라이드 내에서 페이지 이동후 슬라이드가 닫기지 않는 버그가 있어 따로 수정하였습니다.
https://github.com/user-attachments/assets/df9a525d-472f-423f-8eb0-0e5198bfa9be
close #109

comming soon 화면 제작

---

src/pages/admin/components/docs/AdminConfirmTable.tsx
src/pages/admin/components/docs/ApplyDetailModal.tsx

- 직렬별로 서로 다른 질문-답변란 수정
---
---
---
closes #112

지원 서류 modal 직렬별 질문-답변란 수정

---

src/components/common/typography/Text.tsx
src/pages/main/MainPage.tsx
src/pages/main/components/PCRotateCarousel.tsx
src/pages/main/components/RotateCarousel.tsx
src/pages/main/components/Tablet/TabletRotateCarousel.tsx

---
- carousel 메모이제이션 적용
- star lazy 로딩 적용
- font swap 적용
---
---
x
resolved #118

모바일 화면 최적화 로딩

---

src/pages/admin/components/docs/AdminConfirmTable.tsx

- 서류 확인 list 페이지네이션 기능 수정
---
---
---
closes #125

서류 확인 페이지 Pagination 기능 수정

---

src/pages/admin/components/docs/TechStack.tsx

- Admin 페이지에서 modal 창에나오는 기술스텍 부분의 내용이 많을때 좌우 스크롤을 추가하여 넘치지 않도록 수정
---
---
X
---
- close #135

기술스텍 부분 좌우 스크롤 추가

---

src/components/feature/header/MainNavigation.tsx
src/pages/apply/components/ApplyNavBox.tsx
src/styles/GlobalStyle.ts

---
- monospace 제거
- GA 미적용 이슈 해결 ( 환경변수 추가 )
---
- 현재 MAC도 monospace가 적용되었기에 monospace전부 제거함.
---
x

MS 폰트 적용 및 GA 미적용 이슈 

---

src/components/feature/header/MainNavigation.tsx
src/constants/DocsTableColumns.tsx
src/pages/admin/components/docs/TechStack.tsx
src/pages/apply/components/ApplyNavBox.tsx
src/styles/GlobalStyle.ts

---
- 윈도우 폰트 미적용 이슈 해결 (#137 )
- Navigation내 화면 글자 세로 정렬 수정 (#137 )
- GA 미적용 이슈 해결 (#137 )
---
x
---
x

Release v1.0.10

---

src/constants/DocsTableColumns.tsx

Fix: 파일 경로 수정

---

src/apis/hooks/admin/docs/useGetTrack.ts
src/pages/admin/AdminDocConfirmPage.tsx

- 어드민페이지 토탈 개수 오류 수정
-
- 
#143

어드민페이지 토탈개수 오류수정

---

src/apis/hooks/admin/docs/useGetTrack.ts

* fix: 전체 지원 인원수 조회 수정
* fix: console.log 삭제
- 전체 지원 인원수 오류 수정
-
-
#143

Release-v1.0.11 (#144)

---

src/apis/hooks/mypage/usePatchMyData.ts
src/pages/admin/components/AdminSearchBar.tsx
src/pages/mypage/MyPage.tsx
src/types/UserInterface.ts

- 검색창 실시간 검색 -> 엔터 검색으로 변경
- 없음
- 없음
#152

Fix/issue #152

---

README.md
src/pages/introduce/components/AboutEvent.tsx
src/pages/introduce/components/CoreTable.tsx
src/pages/introduce/components/IntroduceEvent.tsx

---
- 메인 페이지 독스 리드미 기능 업데이트 및 내용 추가
---
- 동아리 운영진 소개 페이지 내용 업데이트 했습니다.
---
x
Resolve #163

메인 화면 리드미 페이지 독스 기능 업데이트

---

src/apis/hooks/yearId/useGetClassYearList.ts
src/pages/admin/components/docs/ClassYearIdDropDown.tsx

- 기수 목록 하드코딩 -> api 조회로 수정
- 없음
#187

feat: 기수 목록 조회 기능 추가

---

src/apis/hooks/yearId/useGetClassYearList.ts
src/pages/admin/components/docs/ClassYearIdDropDown.tsx
src/pages/admin/components/docs/Memo.tsx

- 어드민페이지 메모 부분 json 형식으로 보이는 현상 수정
- 
- 없음
#193

어드민페이지 메모 부분 json 형식으로 보이는 현상 수정

---

src/components/feature/header/StatusDropDownItems.tsx
src/router/Router.tsx

- 마이페이지 주석 처리
- 나중에 마이페이지 기능 다시 이용할 것을 대비해 주석 처리
- 
- 
- 없음
#192

fix: 마이페이지 주석처리

---

src/pages/admin/components/docs/ApplyDetailModal.tsx
src/pages/admin/components/docs/Memo.tsx

- 모달창 닫았다가 열었을 때 메모 업데이트 되도록 수정
- alert에 에러메시지 추가
- 
-
- 없음
#190

fix: 모달창 닫았다 다시 열었을 때 메모 업데이트 되는 기능 추가

---

src/pages/admin/AdminDocConfirmPage.tsx

fix: 서류확인페이지 lint 오류 수정
